CELL_SIZE: int = 6
WINDOW_HEIGHT: int = 900
SUB_SQUARE_COLOR: tuple[int, int, int] = 255, 255, 255
WINDOW_WIDTH: int = 950
PENCIL: str = "Pencil"
ERASER: str = "Eraser"
IT_DELAY: float = 0.1  # seconds
SIZE_SQUARE_SIZE: int = 60
SIZE_SUB_SQUARE_SIZE: int = 20
TOOLS_FONT_SIZE: int = 15
OUTLINE_COLOR: tuple[int, int, int] = 255, 255, 255
IMMEDIATE_NEIGHBOURS: list[tuple[int, int]] = [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (-1, 1), (1, -1), (-1, -1)]
BOARD_SIZE: tuple[int, int] = 700, 700
BACKGROUND: tuple[int, int, int] = 27, 32, 39
ALIVE_COLOR: tuple[int, int, int] = 170, 79, 30
DEAD_COLOR: tuple[int, int, int] = 35, 40, 49
BLOCK_FONT: str = "data/fonts/block_font.TTF"
TITLE_FONT_SIZE: int = 30
DEFAULT_PAD: int = 15
RIGHT_ARROW: str = ">"
LEFT_ARROW: str = "<"
MOUSECLICK_LEFT: int = 1
CONTROL_FONT_SIZE: int = 25
HOVER_COLOR: tuple[int, int, int] = 255, 255, 255
HOVER_ALPHA: int = 20
CELL_HOVER_ALPHA: int = 100
SPEED_STEP: float = 1.1
RANDO: str = "rando"
RESET: str = "reset"
PLAY: str = ">"
STOP: str = "||"

# -- JSON --
JSON_FILE_MODE: str = "r"
RULES_JSON: str = "data/variations.json"
DATA: str = "Data"
NAME: str = "Name"
BIRTH: str = "Birth"
SURVIVAL: str = "Survival"
